#include "Utils/NeovimOracle.h"

#include <msgpack.hpp>

#include <fcntl.h>
#include <poll.h>
#include <signal.h>
#include <sys/wait.h>
#include <unistd.h>

#include <sstream>
#include <stdexcept>

/*
* Generated by Claude Code
* 
* For purposes of Vimficiency, we can treat this as a black box, but high-level architecture is:
*  Code <--msgpack-rpc--> nvim --embed --headless
*  --embed allows Neovim to act like a server that speaks in terms of msgpack over stdin/stdout
*/


namespace {
// Neovim RPC message types
constexpr int RPC_REQUEST = 0;
constexpr int RPC_RESPONSE = 1;
} // namespace

struct NeovimOracle::Impl {
  pid_t nvim_pid = -1;
  int stdin_fd = -1;  // Write to nvim
  int stdout_fd = -1; // Read from nvim
  uint32_t msg_id = 0;

  msgpack::sbuffer send_buf;
  msgpack::unpacker recv_unpacker;

  Impl() { recv_unpacker.reserve_buffer(65536); }

  ~Impl() { shutdown(); }

  void shutdown() {
    if (stdin_fd >= 0) {
      close(stdin_fd);
      stdin_fd = -1;
    }
    if (stdout_fd >= 0) {
      close(stdout_fd);
      stdout_fd = -1;
    }
    if (nvim_pid > 0) {
      kill(nvim_pid, SIGTERM);
      waitpid(nvim_pid, nullptr, 0);
      nvim_pid = -1;
    }
  }

  void start() {
    int stdin_pipe[2];  // Parent writes to [1], child reads from [0]
    int stdout_pipe[2]; // Child writes to [1], parent reads from [0]

    if (pipe(stdin_pipe) < 0 || pipe(stdout_pipe) < 0) {
      throw std::runtime_error("Failed to create pipes for Neovim");
    }

    nvim_pid = fork();
    if (nvim_pid < 0) {
      throw std::runtime_error("Failed to fork for Neovim");
    }

    if (nvim_pid == 0) {
      // Child process
      close(stdin_pipe[1]);
      close(stdout_pipe[0]);

      dup2(stdin_pipe[0], STDIN_FILENO);
      dup2(stdout_pipe[1], STDOUT_FILENO);

      close(stdin_pipe[0]);
      close(stdout_pipe[1]);

      execlp("nvim", "nvim", "--embed", "--headless", "-u", "NONE", "-n",
             nullptr);
      _exit(127);
    }

    // Parent process
    close(stdin_pipe[0]);
    close(stdout_pipe[1]);

    stdin_fd = stdin_pipe[1];
    stdout_fd = stdout_pipe[0];

    // Set stdout to non-blocking for reads
    int flags = fcntl(stdout_fd, F_GETFL, 0);
    fcntl(stdout_fd, F_SETFL, flags | O_NONBLOCK);
  }

  void send_request(const std::string &method, const msgpack::object &args) {
    send_buf.clear();
    msgpack::packer<msgpack::sbuffer> pk(&send_buf);

    pk.pack_array(4);
    pk.pack(RPC_REQUEST);
    pk.pack(msg_id++);
    pk.pack(method);
    pk.pack(args);

    ssize_t written = write(stdin_fd, send_buf.data(), send_buf.size());
    if (written != static_cast<ssize_t>(send_buf.size())) {
      throw std::runtime_error("Failed to write request to Neovim");
    }
  }

  msgpack::object_handle recv_response() {
    while (true) {
      msgpack::object_handle oh;
      if (recv_unpacker.next(oh)) {
        auto &obj = oh.get();
        if (obj.type != msgpack::type::ARRAY || obj.via.array.size < 3) {
          throw std::runtime_error("Invalid RPC response format");
        }
        int type = obj.via.array.ptr[0].as<int>();
        if (type == RPC_RESPONSE) {
          // [type=1, msgid, error, result]
          if (obj.via.array.size < 4) {
            throw std::runtime_error("Invalid response array size");
          }
          auto &error = obj.via.array.ptr[2];
          if (error.type != msgpack::type::NIL) {
            std::ostringstream oss;
            oss << "Neovim error: " << error;
            throw std::runtime_error(oss.str());
          }
          return oh;
        }
        // Skip notifications (type=2), keep reading
        continue;
      }

      // Need more data
      struct pollfd pfd = {stdout_fd, POLLIN, 0};
      int ret = poll(&pfd, 1, 5000); // 5 second timeout
      if (ret <= 0) {
        throw std::runtime_error("Timeout waiting for Neovim response");
      }

      ssize_t n = read(stdout_fd, recv_unpacker.buffer(),
                       recv_unpacker.buffer_capacity());
      if (n <= 0) {
        throw std::runtime_error("Failed to read from Neovim");
      }
      recv_unpacker.buffer_consumed(static_cast<size_t>(n));
    }
  }

  // Helper to call Neovim API and get result
  template <typename... Args>
  msgpack::object_handle call(const std::string &method, Args &&...args) {
    msgpack::zone z;
    std::tuple<Args...> arg_tuple(std::forward<Args>(args)...);
    msgpack::object args_obj(arg_tuple, z);
    send_request(method, args_obj);
    return recv_response();
  }

  int64_t call_int(const std::string &method, const msgpack::object &args) {
    send_request(method, args);
    auto oh = recv_response();
    return oh.get().via.array.ptr[3].as<int64_t>();
  }

  void call_void(const std::string &method, const msgpack::object &args) {
    send_request(method, args);
    recv_response(); // Just wait for completion
  }

  // Set window height to match our default NavContext (39 lines)
  // This ensures scroll commands (<C-b>, <C-f>, etc.) behave consistently
  void configureWindowSize() {
    msgpack::zone z;
    // nvim_win_set_height(0, 39) - window 0 is current window
    auto args = msgpack::object(std::make_tuple(0, 39), z);
    call_void("nvim_win_set_height", args);
  }
};

NeovimOracle::NeovimOracle() : impl_(std::make_unique<Impl>()) {
  impl_->start();
  impl_->configureWindowSize();
}

NeovimOracle::~NeovimOracle() = default;

void NeovimOracle::restart() {
  impl_->shutdown();
  impl_->recv_unpacker.reset();
  impl_->recv_unpacker.reserve_buffer(65536);
  impl_->msg_id = 0;
  impl_->start();
  impl_->configureWindowSize();
}

SimulationResult NeovimOracle::simulate(const Lines &lines,
                                        int startRow, int startCol,
                                        const std::string &keys) {
  msgpack::zone z;

  // nvim_create_buf(listed=false, scratch=true)
  {
    auto args = msgpack::object(std::make_tuple(false, true), z);
    impl_->send_request("nvim_create_buf", args);
  }
  auto buf_oh = impl_->recv_response();
  auto &buf_resp = buf_oh.get();
  auto &buf_result = buf_resp.via.array.ptr[3];
  // Buffer handle comes as EXT type 0; extract the integer from the ext data
  int64_t buf = 0;
  if (buf_result.type == msgpack::type::EXT) {
    // EXT data contains the buffer ID as a msgpack integer
    const char *data = buf_result.via.ext.data();
    size_t size = buf_result.via.ext.size;
    if (size == 1) {
      buf = static_cast<uint8_t>(data[0]);
    } else if (size > 1) {
      // Multi-byte integer encoding
      msgpack::object_handle oh = msgpack::unpack(data, size);
      buf = oh.get().as<int64_t>();
    }
  } else {
    buf = buf_result.as<int64_t>();
  }

  // nvim_buf_set_lines(buf, 0, -1, false, lines)
  // Convert Lines to vector<string> for msgpack serialization
  {
    std::vector<std::string> linesVec(lines.begin(), lines.end());
    auto args = msgpack::object(std::make_tuple(buf, 0, -1, false, linesVec), z);
    impl_->call_void("nvim_buf_set_lines", args);
  }

  // nvim_set_current_buf(buf)
  {
    auto args = msgpack::object(std::make_tuple(buf), z);
    impl_->call_void("nvim_set_current_buf", args);
  }

  // nvim_win_set_cursor(0, [row+1, col]) -- Neovim uses 1-indexed rows
  {
    std::vector<int64_t> pos = {startRow + 1, startCol};
    auto args = msgpack::object(std::make_tuple(0, pos), z);
    impl_->call_void("nvim_win_set_cursor", args);
  }

  // Use nvim_input (preserves mode correctly) then force processing via
  // nvim_exec_lua
  {
    auto args = msgpack::object(std::make_tuple(keys), z);
    impl_->send_request("nvim_input", args);
    impl_->recv_response();
  }
  // Force event loop to process the input
  {
    std::vector<msgpack::object> empty_args;
    auto args = msgpack::object(std::make_tuple("return nil", empty_args), z);
    impl_->send_request("nvim_exec_lua", args);
    impl_->recv_response();
  }

  // Get final state
  SimulationResult result;

  // nvim_buf_get_lines(buf, 0, -1, false)
  {
    auto args = msgpack::object(std::make_tuple(buf, 0, -1, false), z);
    impl_->send_request("nvim_buf_get_lines", args);
  }
  auto lines_oh = impl_->recv_response();
  auto &lines_arr = lines_oh.get().via.array.ptr[3].via.array;
  result.lines.reserve(lines_arr.size);
  for (size_t i = 0; i < lines_arr.size; ++i) {
    result.lines.push_back(lines_arr.ptr[i].as<std::string>());
  }

  // nvim_win_get_cursor(0)
  {
    auto args = msgpack::object(std::make_tuple(0), z);
    impl_->send_request("nvim_win_get_cursor", args);
  }
  auto cursor_oh = impl_->recv_response();
  auto &cursor_arr = cursor_oh.get().via.array.ptr[3].via.array;
  result.row = cursor_arr.ptr[0].as<int>() - 1; // Convert to 0-indexed
  result.col = cursor_arr.ptr[1].as<int>();

  // nvim_get_mode()
  {
    auto args = msgpack::object(std::make_tuple(), z);
    impl_->send_request("nvim_get_mode", args);
  }
  auto mode_oh = impl_->recv_response();
  auto &mode_result = mode_oh.get().via.array.ptr[3];
  std::string mode_str;
  if (mode_result.type == msgpack::type::MAP) {
    for (size_t i = 0; i < mode_result.via.map.size; ++i) {
      auto &kv = mode_result.via.map.ptr[i];
      if (kv.key.as<std::string>() == "mode") {
        mode_str = kv.val.as<std::string>();
        break;
      }
    }
  }
  if (mode_str == "i" || mode_str == "ic" || mode_str == "ix") {
    result.mode = Mode::Insert;
  } else if (mode_str == "v" || mode_str == "V" || mode_str == "\x16") {
    result.mode = Mode::Visual;
  } else {
    result.mode = Mode::Normal;
  }

  // Return to normal mode and clean up buffer
  {
    // Send Escape to ensure we're in normal mode
    auto args = msgpack::object(std::make_tuple("\x1b"), z);
    impl_->send_request("nvim_input", args);
    impl_->recv_response();
  }
  // Force processing of Escape
  {
    std::vector<msgpack::object> empty_args;
    auto args = msgpack::object(std::make_tuple("return nil", empty_args), z);
    impl_->send_request("nvim_exec_lua", args);
    impl_->recv_response();
  }

  // nvim_buf_delete(buf, {force=true})
  {
    std::map<std::string, bool> opts = {{"force", true}};
    auto args = msgpack::object(std::make_tuple(buf, opts), z);
    impl_->call_void("nvim_buf_delete", args);
  }

  return result;
}
